// <auto-generated />
using System;
using LeadPilot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeadPilot.Migrations
{
    [DbContext(typeof(LeadPilotDbContext))]
    [Migration("20260310144621_SeedDataConfigurationsForAllEntities")]
    partial class SeedDataConfigurationsForAllEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeadPilot.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmailTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmailTypeID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SouceId")
                        .HasColumnType("integer")
                        .HasColumnName("SouceID");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Email_Template_pkey");

                    b.HasIndex("EmailTypeId");

                    b.HasIndex("SouceId");

                    b.ToTable("Email_Template", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Body = "<p>Hi@ContactName,</p><p> I came across @FirmName while researching businesses in @City and wanted to reach out.</p><p> Quick question — are you currently exploring ways to improve internal workflows or automate any repetitive processes?</p><p>I build custom tools and automations that help teams save time and reduce manual work.</p><p>No sales pitch — just curious if this is something on your radar.</p><p style = \"margin-top:25px;\">Best regards,  <br/>Krunal</p>",
                            EmailTypeId = 1,
                            Name = "Initial",
                            Subject = "Quick question about your internal workflows"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Body = "<p>Hi@ContactName,</p>\r\n\r\n<p>Just following up on my earlier note.</p>\r\n\r\n<p>If improving internal workflows or operational efficiency is on your roadmap, I’d be happy to explore whether there’s a good fit.</p>\r\n\r\n<p style=\"margin-top:25px;\">\r\nBest regards,<br/>\r\nKrunal Pagdar<br/>\r\nFull-Stack Developer (.NET | Azure)\r\n</p>",
                            EmailTypeId = 2,
                            Name = "FollowUp",
                            Subject = "Following up"
                        });
                });

            modelBuilder.Entity("LeadPilot.Models.EmailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Email_Type_pkey");

                    b.ToTable("Email_Type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Initial"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Name = "Followup"
                        });
                });

            modelBuilder.Entity("LeadPilot.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AddedOn")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EmailID");

                    b.Property<bool>("Inactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceID");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("StatusID");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Primary_Key_Lead");

                    b.HasIndex(new[] { "Inactive" }, "IDX_Inactive")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "StatusId" }, "IDX_Status")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "AddedOn" }, "Idx_Addedon")
                        .IsDescending()
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Website" }, "Uni_Website")
                        .IsUnique();

                    b.HasIndex(new[] { "SourceId" }, "idx_Source")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("Lead", (string)null);
                });

            modelBuilder.Entity("LeadPilot.Models.LeadEmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("EmailTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("EmailTemplateID");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("LeadID");

                    b.Property<DateOnly>("MailDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NextEmailDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("LeadEmailLog_pkey");

                    b.HasIndex("EmailTemplateId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadEmailLog", (string)null);
                });

            modelBuilder.Entity("LeadPilot.Models.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Lead_Source_pkey");

                    b.ToTable("Lead_Source", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Google Map"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Name = "HotFrog"
                        });
                });

            modelBuilder.Entity("LeadPilot.Models.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Lead_Status_pkey");

                    b.ToTable("Lead_Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Active = true,
                            Name = "New"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Name = "InitialSent"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Name = "FollowUpSent"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Name = "Replied"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Name = "Closed"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Name = "DoNotContact"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Name = "NotInterested"
                        });
                });

            modelBuilder.Entity("LeadPilot.Models.EmailTemplate", b =>
                {
                    b.HasOne("LeadPilot.Models.EmailType", "EmailType")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("EmailTypeId")
                        .IsRequired()
                        .HasConstraintName("Email_Type_Email_Template");

                    b.HasOne("LeadPilot.Models.LeadSource", "Souce")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("SouceId")
                        .HasConstraintName("LeadSource_EmailTemplate");

                    b.Navigation("EmailType");

                    b.Navigation("Souce");
                });

            modelBuilder.Entity("LeadPilot.Models.Lead", b =>
                {
                    b.HasOne("LeadPilot.Models.LeadSource", "Source")
                        .WithMany("Leads")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("Lead_source");

                    b.HasOne("LeadPilot.Models.LeadStatus", "Status")
                        .WithMany("Leads")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("Lead_status");

                    b.Navigation("Source");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LeadPilot.Models.LeadEmailLog", b =>
                {
                    b.HasOne("LeadPilot.Models.EmailTemplate", "EmailTemplate")
                        .WithMany("LeadEmailLogs")
                        .HasForeignKey("EmailTemplateId")
                        .IsRequired()
                        .HasConstraintName("Lead_TemplateID");

                    b.HasOne("LeadPilot.Models.Lead", "Lead")
                        .WithMany("LeadEmailLogs")
                        .HasForeignKey("LeadId")
                        .IsRequired()
                        .HasConstraintName("Lead_EmailLog");

                    b.Navigation("EmailTemplate");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadPilot.Models.EmailTemplate", b =>
                {
                    b.Navigation("LeadEmailLogs");
                });

            modelBuilder.Entity("LeadPilot.Models.EmailType", b =>
                {
                    b.Navigation("EmailTemplates");
                });

            modelBuilder.Entity("LeadPilot.Models.Lead", b =>
                {
                    b.Navigation("LeadEmailLogs");
                });

            modelBuilder.Entity("LeadPilot.Models.LeadSource", b =>
                {
                    b.Navigation("EmailTemplates");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("LeadPilot.Models.LeadStatus", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
