// <auto-generated />
using System;
using LeadPilot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeadPilot.Migrations
{
    [DbContext(typeof(LeadPilotDbContext))]
    partial class LeadPilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeadPilot.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmailTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmailTypeID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SouceId")
                        .HasColumnType("integer")
                        .HasColumnName("SouceID");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Email_Template_pkey");

                    b.HasIndex("EmailTypeId");

                    b.HasIndex("SouceId");

                    b.ToTable("Email_Template", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Body = "<p>Hi@ContactName,</p>\r\n\r\n<p>I came across @FirmName while reviewing accounting firms in @City and wanted to reach out directly. I work with professional services firms to improve internal systems and streamline day-to-day operations.</p>\r\n\r\n<p>If improving internal efficiency or reducing manual effort is something you’re considering this year, would you be open to a short conversation to see if there’s a fit?</p>\r\n\r\n<p style=\"margin-top:25px;\">\r\nBest regards,<br/>\r\nKrunal Pagdar<br/>\r\nFull-Stack Developer (.NET | Azure)\r\n</p>",
                            EmailTypeId = 1,
                            Name = "GoogleMap - Initial",
                            SouceId = 1,
                            Subject = "Quick question about your internal workflows"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Body = "<p>Hi@ContactName,</p>\r\n\r\n<p>I came across @FirmName while reviewing accounting firms listed on Hotfrog and wanted to reach out directly. I work with professional services firms to improve internal systems and streamline day-to-day operations.</p>\r\n\r\n<p>If improving internal efficiency is something you’re exploring this year, I’d be happy to have a quick conversation.</p>\r\n\r\n<p style=\"margin-top:25px;\">\r\nBest regards,<br/>\r\nKrunal Pagdar<br/>\r\nFull-Stack Developer (.NET | Azure)\r\n</p>",
                            EmailTypeId = 1,
                            Name = "HotFrog - Initial",
                            SouceId = 2,
                            Subject = "Quick question after finding @FirmName on Hotfrog"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Body = "<p>Hi@ContactName,</p>\r\n\r\n<p>Just following up on my earlier note.</p>\r\n\r\n<p>If improving internal workflows or operational efficiency is on your roadmap, I’d be happy to explore whether there’s a good fit.</p>\r\n\r\n<p style=\"margin-top:25px;\">\r\nBest regards,<br/>\r\nKrunal Pagdar<br/>\r\nFull-Stack Developer (.NET | Azure)\r\n</p>",
                            EmailTypeId = 2,
                            Name = "FollowUp",
                            Subject = "Following up"
                        });
                });

            modelBuilder.Entity("LeadPilot.Models.EmailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Email_Type_pkey");

                    b.ToTable("Email_Type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Initial"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Name = "Followup"
                        });
                });

            modelBuilder.Entity("LeadPilot.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AddedOn")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EmailID");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceID");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("StatusID");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Primary_Key_Lead");

                    b.HasIndex("SourceId");

                    b.HasIndex("StatusId");

                    b.ToTable("Lead", (string)null);
                });

            modelBuilder.Entity("LeadPilot.Models.LeadEmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("EmailTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("EmailTemplateID");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("LeadID");

                    b.Property<DateOnly>("MailDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NextEmailDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("LeadEmailLog_pkey");

                    b.HasIndex("EmailTemplateId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadEmailLog", (string)null);
                });

            modelBuilder.Entity("LeadPilot.Models.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Lead_Source_pkey");

                    b.ToTable("Lead_Source", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Google Map"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Name = "HotFrog"
                        });
                });

            modelBuilder.Entity("LeadPilot.Models.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Lead_Status_pkey");

                    b.ToTable("Lead_Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Active = true,
                            Name = "New"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Name = "InitialSent"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Name = "FollowUpSent"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Name = "Replied"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Name = "Closed"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Name = "DoNotContact"
                        });
                });

            modelBuilder.Entity("LeadPilot.Models.EmailTemplate", b =>
                {
                    b.HasOne("LeadPilot.Models.EmailType", "EmailType")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("EmailTypeId")
                        .IsRequired()
                        .HasConstraintName("Email_Type_Email_Template");

                    b.HasOne("LeadPilot.Models.LeadSource", "Souce")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("SouceId")
                        .HasConstraintName("LeadSource_EmailTemplate");

                    b.Navigation("EmailType");

                    b.Navigation("Souce");
                });

            modelBuilder.Entity("LeadPilot.Models.Lead", b =>
                {
                    b.HasOne("LeadPilot.Models.LeadSource", "Source")
                        .WithMany("Leads")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("Lead_source");

                    b.HasOne("LeadPilot.Models.LeadStatus", "Status")
                        .WithMany("Leads")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("Lead_status");

                    b.Navigation("Source");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LeadPilot.Models.LeadEmailLog", b =>
                {
                    b.HasOne("LeadPilot.Models.EmailTemplate", "EmailTemplate")
                        .WithMany("LeadEmailLogs")
                        .HasForeignKey("EmailTemplateId")
                        .IsRequired()
                        .HasConstraintName("Lead_TemplateID");

                    b.HasOne("LeadPilot.Models.Lead", "Lead")
                        .WithMany("LeadEmailLogs")
                        .HasForeignKey("LeadId")
                        .IsRequired()
                        .HasConstraintName("Lead_EmailLog");

                    b.Navigation("EmailTemplate");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadPilot.Models.EmailTemplate", b =>
                {
                    b.Navigation("LeadEmailLogs");
                });

            modelBuilder.Entity("LeadPilot.Models.EmailType", b =>
                {
                    b.Navigation("EmailTemplates");
                });

            modelBuilder.Entity("LeadPilot.Models.Lead", b =>
                {
                    b.Navigation("LeadEmailLogs");
                });

            modelBuilder.Entity("LeadPilot.Models.LeadSource", b =>
                {
                    b.Navigation("EmailTemplates");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("LeadPilot.Models.LeadStatus", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
